# Generated by Django 3.2.5 on 2021-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='allowance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_spent',
            field=models.FloatField(),
        ),
    ]
